version: "3.4"

services:
  web:
    build: .
    env_file:
      - .env
    user: "${UID}:${GID}"
    working_dir: /srv/app
    stdin_open: true  # `-i`
    tty: true  # `-t`
    volumes:
       - ${PWD}:/srv/app
    network_mode: host
